name: 'ssm-to-heroku-env-action'
description: 'Pass SSM ParameterStore values to Heroku ENV variables'
author: 'iisyos'
inputs:
  path:
    required: true
    description: 'the path to your SSM ParameterStore'
  email:
    required: true
    description: 'Heroku email'
  token:
    required: true
    description: 'Heroku token'
  app:
    required: true
    description: 'Heroku app name'
runs:
  using: 'node16'
  main: 'dist/index.js'
